### ISSUE TITLE
Segfault in zeroconf_avahi lib

### ISSUE THREAD

**Issue by rgariepy** [rosjava/zeroconf_jmdns_suite#35]
Worked reliably, then started getting a segfault on system startup (reliably). When I commented out the logging lines on and following line 610 in zeroconf.cpp, I saw no more instances. Debugged using the gdb launch-prefix in roslaunch.

Backtrace:
[Switching to Thread 0xb4f91b70 (LWP 31296)]
0x003784e3 in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/i386-linux-gnu/libstdc++.so.6
(gdb) backtrace\
^CQuit
#0  0x003784e3 in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#1  0x002dadf4 in zeroconf_avahi::Zeroconf::resolve_callback (

```
resolver=0x8087ac8, interface=3, protocol=0, event=AVAHI_RESOLVER_FOUND, 
name=0x2e957b "][", type=0x808a6e8 "_ros-master._tcp", 
domain=0x8084558 "local", host_name=0x808b1b8 "\001", address=0xb4f90c5c, 
port=0, txt=0x0, flags=0, userdata=0xbfffeef8)
at /home/user/<REDACTED>/zeroconf_implementations/zeroconf_avahi/src/lib/zeroconf.cpp:610
```
#2  0x008cdfbb in avahi_service_resolver_event ()

   from /usr/lib/i386-linux-gnu/libavahi-client.so.3
#3  0x008c73c4 in ?? () from /usr/lib/i386-linux-gnu/libavahi-client.so.3
#4  0x00c4c441 in dbus_connection_dispatch ()

   from /lib/i386-linux-gnu/libdbus-1.so.3
#5  0x008d025b in ?? () from /usr/lib/i386-linux-gnu/libavahi-client.so.3
#6  0x00c8ec37 in ?? () from /usr/lib/i386-linux-gnu/libavahi-common.so.3
#7  0x00c8f003 in avahi_simple_poll_dispatch ()

   from /usr/lib/i386-linux-gnu/libavahi-common.so.3
#8  0x00c8f18e in avahi_simple_poll_iterate ()

   from /usr/lib/i386-linux-gnu/libavahi-common.so.3
#9  0x00c8f356 in avahi_simple_poll_loop ()

---Type <return> to continue, or q <return> to quit---
   from /usr/lib/i386-linux-gnu/libavahi-common.so.3
#10 0x00c8f494 in ?? () from /usr/lib/i386-linux-gnu/libavahi-common.so.3
#11 0x007bcd31 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#12 0x004cd46e in clone () from /lib/i386-linux-gnu/libc.so.6

Backtrace stopped: Not enough registers or memory available to unwind further

**Comment by stonier** [comment]
Thanks Ryan.

Been a bit busy here preparing for a workshop last week, but will look at it shortly. Send me pull requests if you find anything more.

**Comment by stonier** [comment]
Reproducing conditions...(just for reference).
- On remote:

```
> avahi-publish -s DudeMaster _ros-master._tcp 3212
```
- Disable the wireless on the remote
- On the local

```
> roslaunch zeroconf_avahi ros_browser.launch
```
