### ISSUE TITLE
zeroconf_jmdns fails to build on Kinetic

### ISSUE THREAD

**Issue by tfoote** [rosjava/zeroconf_jmdns_suite#55]
It looks to be the same issue with gradle version as rosjava/rosjava_core#288

http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__zeroconf_jmdns_suite__ubuntu_xenial_amd64__binary/19/console

**Comment by jubeira** [comment]
PR with patch here: https://github.com/ros/rosdistro/pull/20030.

Thanks again @tfoote !
